name: Writers Whirled
favicon: null
layout_spectrum: 0.02004820480942726
typography_spectrum: 0.45637298561632633
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.17384787579067051
  lightness: 0.5217698416672647
  saturation: 0.3632036915514618
  rhythmicContrast: 0.4537927347701043
purpose: []
